#! /bin/sh
# /etc/init.d/teamcity
#

# Carry out specific functions when asked to by the system
case "$1" in
start)
echo "Starting TeamCity "
/opt/TeamCity/bin/runAll.sh start
;;
stop)
echo "Stopping script teamcity"
/opt/TeamCity/bin/runAll.sh stop
;;
*)
echo "Usage: /etc/init.d/teamcity
Unknown macro: {start|stop}
"
exit 1
;;
esac
exit 0
